### PR TITLE
Report parameter seeds in AssertionErrors

### LINKED ISSUE #92: Report seed in test runner for failed tests
Re-running a failed test requires to retrieve the seed from the log file as [described in the documentation](https://pholser.github.io/junit-quickcheck/site/0.6-beta-1/usage/seed.html). It would be much more convenient to have the seed reported by the test runner (`PropertyStatement.evaluate()`) instead.
I also wonder if it wouldn't be easier to use a single seed for all parameters.

### PR DESCRIPTION
**Pull request by spodkowinski**
This would be a pretty simple way to report seeds by just passing the seeds along with the generated args.

Fixes #92

### CODE REVIEW

**Comment by pholser** [comment]
@spodkowinski Thanks for this! Looks really good. I'll review more carefully, and if I have any suggestions I'll comment inline.

I will likely declare a 0.6 very soon, then pull this in (after any adjustments) after that. How does that sound?

**Comment by spodkowinski** [comment]
Pushed new commit that addresses most of your suggestions (thanks!).
I'd consider this a minor change, but it's of course up to you if you want to make this part of 0.6.

**Comment by pholser** [comment]
@spodkowinski I've started addressing outstanding pull requests...it seems that once I got to yours, there are conflicts. Would you mind to resolve them in your branch, and I'll merge after that? Thanks!

**Comment by spodkowinski** [comment]
I've just rebased and my branch and resolved the small conflict.

**Pull request merged**
